# Exercise on Functions:

# Task-1 Unit Conversion

In [1]:
def convert_length(value, unit):
    """Convert length between meters and feet.

    Parameters:
    value (float): Value to be converted.
    unit (str): Conversion type ('m_to_ft' or 'ft_to_m').

    Returns:
    float: Converted value.

    Raises:
    ValueError: If an invalid unit is provided.
    """
    if unit == 'm_to_ft':
        return value * 3.28084  # Convert meters to feet
    elif unit == 'ft_to_m':
        return value / 3.28084  # Convert feet to meters
    else:
        raise ValueError("Invalid length conversion type.")  # Handle invalid input

def convert_weight(value, unit):
    """Convert weight between kilograms and pounds.

    Parameters:
    value (float): Value to be converted.
    unit (str): Conversion type ('kg_to_lbs' or 'lbs_to_kg').

    Returns:
    float: Converted value.

    Raises:
    ValueError: If an invalid unit is provided.
    """
    if unit == 'kg_to_lbs':
        return value * 2.20462  # Convert kg to pounds
    elif unit == 'lbs_to_kg':
        return value / 2.20462  # Convert pounds to kg
    else:
        raise ValueError("Invalid weight conversion type.")  # Handle invalid input

def convert_volume(value, unit):
    """Convert volume between liters and gallons.

    Parameters:
    value (float): Value to be converted.
    unit (str): Conversion type ('L_to_gal' or 'gal_to_L').

    Returns:
    float: Converted value.

    Raises:
    ValueError: If an invalid unit is provided.
    """
    if unit == 'L_to_gal':
        return value * 0.264172  # Convert liters to gallons
    elif unit == 'gal_to_L':
        return value / 0.264172  # Convert gallons to liters
    else:
        raise ValueError("Invalid volume conversion type.")  # Handle invalid input

def main():
    """Run the unit converter program, allowing users to select a conversion, input a value, and get the result."""
    print("Welcome to the Unit Converter!")  # Display welcome message
    print("Available conversions:")
    print("1. Length: meters <-> feet")
    print("2. Weight: kilograms <-> pounds")
    print("3. Volume: liters <-> gallons")

    try:
        conversion_type = int(input("Choose conversion type (1, 2, or 3): "))  # Get category
        value = float(input("Enter the value to convert: "))  # Get numeric input

        if conversion_type == 1:
            unit = input("Enter conversion (m_to_ft or ft_to_m): ")
            result = convert_length(value, unit)  # Perform length conversion
        elif conversion_type == 2:
            unit = input("Enter conversion (kg_to_lbs or lbs_to_kg): ")
            result = convert_weight(value, unit)  # Perform weight conversion
        elif conversion_type == 3:
            unit = input("Enter conversion (L_to_gal or gal_to_L): ")
            result = convert_volume(value, unit)  # Perform volume conversion
        else:
            print("Invalid conversion type.")  # Handle incorrect selection
            return

        print(f"Converted value: {result}")  # Display result

    except ValueError as e:
        print(f"Error: {e}")  # Handle invalid input

main()  # Run the program


Welcome to the Unit Converter!
Available conversions:
1. Length: meters <-> feet
2. Weight: kilograms <-> pounds
3. Volume: liters <-> gallons
Choose conversion type (1, 2, or 3): 1
Enter the value to convert: 10
Enter conversion (m_to_ft or ft_to_m): m_to_ft
Converted value: 32.8084


# Task-2 Math Operation on List of Numbers

In [2]:
def calculate_sum(numbers):
    """Return the sum of a list of numbers.

    Parameters:
    numbers (list): List of numerical values.

    Returns:
    float: Sum of all elements.
    """
    return sum(numbers)

def calculate_average(numbers):
    """Return the average of a list of numbers.

    Parameters:
    numbers (list): List of numerical values.

    Returns:
    float: Average of the elements.
    """
    return sum(numbers) / len(numbers)  # Prevents division by zero error

def find_maximum(numbers):
    """Return the maximum value in a list.

    Parameters:
    numbers (list): List of numerical values.

    Returns:
    float: Maximum element.
    """
    return max(numbers)  # Finds the highest value

def find_minimum(numbers):
    """Return the minimum value in a list.

    Parameters:
    numbers (list): List of numerical values.

    Returns:
    float: Minimum element.
    """
    return min(numbers)  # Finds the lowest value

def main():
    """Run the program to perform mathematical operations."""
    print("Welcome to the Mathematical Operations Program!")  # Greeting message
    print("Select an operation:")
    print("1. Sum  2. Average  3. Maximum  4. Minimum")  # Options

    try:
        operation = int(input("Choose an operation (1-4): "))  # User input for operation
        numbers = list(map(float, input("Enter numbers separated by spaces: ").split()))  # Input list

        if operation == 1:
            print(f"Sum: {calculate_sum(numbers)}")  # Display sum
        elif operation == 2:
            print(f"Average: {calculate_average(numbers)}")  # Display average
        elif operation == 3:
            print(f"Maximum: {find_maximum(numbers)}")  # Display max value
        elif operation == 4:
            print(f"Minimum: {find_minimum(numbers)}")  # Display min value
        else:
            print("Invalid operation selected.")  # Handle incorrect choice

    except ValueError as e:
        print(f"Error: {e}")  # Handle non-numeric input
    except ZeroDivisionError:
        print("Error: Cannot calculate average of an empty list.")  # Handle empty list case

main()  # Run the program


Welcome to the Mathematical Operations Program!
Select an operation:
1. Sum  2. Average  3. Maximum  4. Minimum
Choose an operation (1-4): 3
Enter numbers separated by spaces: 1 4 6 8
Maximum: 8.0


# Exercise on List Manipulation:

In [3]:
def extract_every_other(lst):
    """
    Extracts every other element from a list, starting from the first element.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A new list containing every other element.
    """
    return lst[::2]  # Selects every second element from the list.

# Example usage
print(extract_every_other([1, 2, 3, 4, 5, 6]))  # Output: [1, 3, 5]


[1, 3, 5]


In [4]:
def get_sublist(lst, start, end):
    """
    Returns a sublist from a given list, starting from a specified index and ending at another specified index.

    Parameters:
    lst (list): The input list.
    start (int): The starting index.
    end (int): The ending index.

    Returns:
    list: The sublist from start to end (inclusive).
    """
    return lst[start:end+1]  # Extracts elements from start to end index (inclusive).


print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))  # Output: [3, 4, 5]


[3, 4, 5]


In [5]:
def reverse_list(lst):
    """
    Reverses a list using slicing.

    Parameters:
    lst (list): The input list.

    Returns:
    list: The reversed list.
    """
    return lst[::-1]  # Reverses the list using slicing.


print(reverse_list([1, 2, 3, 4, 5]))  # Output: [5, 4, 3, 2, 1]


[5, 4, 3, 2, 1]


In [6]:
def remove_first_last(lst):
    """
    Removes the first and last elements of a list and returns the resulting sublist.

    Parameters:
    lst (list): The input list.

    Returns:
    list: The sublist without the first and last elements.
    """
    return lst[1:-1]  # Extracts all elements except the first and last.

print(remove_first_last([1, 2, 3, 4, 5]))  # Output: [2, 3, 4]


[2, 3, 4]


In [7]:
def get_first_n(lst, n):
    """
    Extracts the first n elements from a list.

    Parameters:
    lst (list): The input list.
    n (int): The number of elements to extract.

    Returns:
    list: The first n elements of the list.
    """
    return lst[:n]  # Slices the list to get the first n elements.


print(get_first_n([1, 2, 3, 4, 5], 3))  # Output: [1, 2, 3]


[1, 2, 3]


In [8]:
def get_last_n(lst, n):
    """
    Extracts the last n elements of a list using slicing.

    Parameters:
    lst (list): The input list.
    n (int): The number of elements to extract.

    Returns:
    list: The last n elements of the list.
    """
    return lst[-n:]  # Slices the list to get the last n elements.


print(get_last_n([1, 2, 3, 4, 5], 2))  # Output: [4, 5]


[4, 5]


In [9]:
def reverse_skip(lst):
    """
    Extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A new list containing every second element starting from the second-to-last, moving backward.
    """
    return lst[-2::-2]  # Extracts every second element starting from the second-to-last, moving backward.


print(reverse_skip([1, 2, 3, 4, 5, 6]))  # Output: [5, 3, 1]


[5, 3, 1]


# Exercise on Nested List

In [10]:
def flatten(lst):
    """
    Flattens a nested list into a single list.

    Parameters:
    lst (list): The nested list.

    Returns:
    list: A flattened version of the list.
    """
    flat_list = []  # Initialize an empty list to store the flattened result.
    for item in lst:
        if isinstance(item, list):  # If the item is a list, recursively flatten it.
            flat_list.extend(flatten(item))
        else:
            flat_list.append(item)  # Otherwise, just append the item.
    return flat_list


print(flatten([[1, 2], [3, [4, 5]], 6]))  # Output: [1, 2, 3, 4, 5, 6]


[1, 2, 3, 4, 5, 6]


In [11]:
def access_nested_element(lst, indices):
    """
    Extracts a specific element from a nested list given its indices.

    Parameters:
    lst (list): The nested list.
    indices (list): A list of indices.

    Returns:
    any: The element at the specified position.
    """
    for index in indices:  # Iterate through each index in the indices list.
        lst = lst[index]  # Update lst to the element at the current index.
    return lst  # Return the final element.


print(access_nested_element([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 2]))  # Output: 6


6


In [12]:
def sum_nested(lst):
    """
    Calculates the sum of all the numbers in a nested list.

    Parameters:
    lst (list): The nested list.

    Returns:
    float: The sum of all elements.
    """
    return sum(flatten(lst))  # Flatten the list and sum all the elements.


print(sum_nested([[1, 2], [3, [4, 5]], 6]))  # Output: 21


21


In [13]:
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.

    Parameters:
    lst (list): The nested list.
    elem (any): The element to remove.

    Returns:
    list: The modified list.
    """
    # Use list comprehension to recursively remove occurrences of elem.
    return [remove_element(item, elem) if isinstance(item, list) else item for item in lst if item != elem]


print(remove_element([[1, 2], [3, 2], [4, 5]], 2))  # Output: [[1], [3], [4, 5]]


[[1], [3], [4, 5]]


In [14]:
def find_max(lst):
    """
    Finds the maximum element in a nested list.

    Parameters:
    lst (list): The nested list.

    Returns:
    float: The maximum element.
    """
    # Flatten the list and return the maximum element
    return max(flatten(lst))


print(find_max([[1, 2], [3, [4, 5]], 6]))  # Output: 6


6


In [15]:
def count_occurrences(lst, elem):
    """
    Counts how many times a specific element appears in a nested list.

    Parameters:
    lst (list): The nested list.
    elem (any): The element to count.

    Returns:
    int: The number of occurrences.
    """
    # Flatten the list and count occurrences of the element
    return flatten(lst).count(elem)


print(count_occurrences([[1, 2], [2, 3], [2, 4]], 2))  # Output: 3


3


In [ ]:
def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single list.

    Parameters:
    lst (list): The deeply nested list.

    Returns:
    list: A single flattened list.
    """
    # Use the flatten function to flatten the deeply nested list
    return flatten(lst)

print(deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))  # Output: [1, 2, 3, 4, 5, 6, 7, 8]


[1, 2, 3, 4, 5, 6, 7, 8]

In [16]:
def average_nested(lst):
    """
    Calculates the average of all elements in a nested list.

    Parameters:
    lst (list): The nested list.

    Returns:
    float: The average of all elements.
    """
    # Flatten the list and calculate the sum and length to compute the average
    flat_list = flatten(lst)
    return sum(flat_list) / len(flat_list)

print(average_nested([[1, 2], [3, 4], [5, 6]]))  # Output: 3.5


3.5


# Basic Vector and Matrix Operation with Numpy.

# Problem - 1: Array Creation:

In [17]:
import numpy as np

# 1. Initialize an empty array with size 2x2
# Creates an uninitialized array with random values
empty_array = np.empty((2, 2))  # Empty array of shape 2x2
print("Empty 2x2 Array:\n", empty_array)
print("---------------")

# 2. Initialize an all ones array with size 4x2
# Creates an array of shape 4x2 filled with ones
ones_array = np.ones((4, 2))  # Array of ones of shape 4x2
print("All Ones 4x2 Array:\n", ones_array)
print("---------------")

# 3. Return a new array of given shape and type, filled with fill value
# This will create a 3x3 array where all values are set to 5
fill_value_array = np.full((3, 3), 5)  # 3x3 array, filled with 5
print("Array Filled with Value 5:\n", fill_value_array)
print("---------------")

# 4. Return a new array of zeros with same shape and type as a given array
# Here, we create a zeros array with the same shape as `given_array`
given_array = np.array([[1, 2], [3, 4]])  # Initial array to match shape
zeros_like_array = np.zeros_like(given_array)  # Zeros array of same shape
print("Zeros Array with Same Shape as Given Array:\n", zeros_like_array)
print("---------------")

# 5. Return a new array of ones with same shape and type as a given array
# Creating an array of ones with the same shape as `given_array`
ones_like_array = np.ones_like(given_array)  # Ones array of same shape
print("Ones Array with Same Shape as Given Array:\n", ones_like_array)
print("---------------")

# 6. Convert a list to a NumPy array
# Converts a plain Python list to a NumPy array
new_list = [1, 2, 3, 4]  # Python list
numpy_array = np.array(new_list)  # Conversion to NumPy array
print("Converted NumPy Array from List:\n", numpy_array)


Empty 2x2 Array:
 [[1.71541460e-316 0.00000000e+000]
 [6.73681725e-310 5.33257700e-317]]
---------------
All Ones 4x2 Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
---------------
Array Filled with Value 5:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]
---------------
Zeros Array with Same Shape as Given Array:
 [[0 0]
 [0 0]]
---------------
Ones Array with Same Shape as Given Array:
 [[1 1]
 [1 1]]
---------------
Converted NumPy Array from List:
 [1 2 3 4]


# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [18]:
import numpy as np

# 1. Generate an array with numbers from 10 to 49
range_array = np.arange(10, 50)
print("Array with Values from 10 to 49:\n", range_array)
print("---------------")

# 2. Generate a 3x3 matrix with numbers from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("3x3 Matrix with Values 0 to 8:\n", matrix_3x3)
print("---------------")

# 3. Create a 3x3 identity matrix with ones on the diagonal
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:\n", identity_matrix)
print("---------------")

# 4. Generate a random array of size 30 and calculate its mean value
random_array = np.random.random(30)
mean_value = random_array.mean()  # Calculate mean of the random numbers
print("Random Array of Size 30:\n", random_array)
print("Mean of Random Array:", mean_value)

# 5. Generate a 10x10 random array and determine its min and max values
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()  # Get the minimum value from the array
max_value = random_10x10.max()  # Get the maximum value from the array
print("10x10 Random Array:\n", random_10x10)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)
print("---------------")

# 6. Create a zero-initialized array of size 10 and set the 5th element to 1
zero_array = np.zeros(10)
zero_array[4] = 1  # Change the 5th element (index 4) to 1
print("Zero Array with 5th Element Replaced:\n", zero_array)
print("---------------")

# 7. Reverse the given array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]  # Reverse the elements of the array
print("Reversed Array:\n", reversed_arr)
print("---------------")

# 8. Generate a 2D array with border of 1s and the inside as 0s
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0  # Set inner values to 0
print("2D Array with 1 on Border and 0 Inside:\n", border_array)
print("---------------")

# 9. Create an 8x8 matrix with a checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1  # Set every alternate element in the first half
checkerboard[::2, 1::2] = 1  # Set every alternate element in the second half
print("8x8 Checkerboard Pattern:\n", checkerboard)


Array with Values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
---------------
3x3 Matrix with Values 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
---------------
3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
---------------
Random Array of Size 30:
 [0.98444102 0.89970782 0.81219096 0.51154644 0.56134828 0.60013742
 0.60776838 0.75380201 0.09322506 0.25270828 0.60709268 0.49145898
 0.15687979 0.79948752 0.97675159 0.70991004 0.15737481 0.08808994
 0.30636068 0.89499672 0.11797024 0.28668167 0.86415388 0.02646106
 0.35502285 0.07068822 0.81379653 0.98874331 0.36503858 0.88171132]
Mean of Random Array: 0.5345182020029126
10x10 Random Array:
 [[0.60871716 0.18147704 0.72957182 0.37786265 0.61098031 0.09067873
  0.91904622 0.5189725  0.30430403 0.16708264]
 [0.0680915  0.97781216 0.6575837  0.58269302 0.06028348 0.53263516
  0.08151694 0.87861736 0.21248819 0.13020856]
 [0.48094508 0.0600967

# Problem - 3: Array Operations:

In [19]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Perform element-wise addition of x and y
add_result = x + y  # Adding corresponding elements of x and y
print("Addition of x and y:\n", add_result)
print("---------------")

# 2. Perform element-wise subtraction of x and y
subtract_result = x - y  # Subtract corresponding elements of x and y
print("Subtraction of x and y:\n", subtract_result)
print("---------------")

# 3. Multiply each element of the array x by 2
multiply_result = x * 2  # Element-wise multiplication of x by 2
print("Multiplication of x by 2:\n", multiply_result)
print("---------------")

# 4. Compute the square of each element in x
square_result = np.square(x)  # Squaring each element in the array x
print("Square of Each Element in x:\n", square_result)
print("---------------")

# 5. Compute the dot product for different arrays
dot_vw = np.dot(v, w)  # Dot product of the vectors v and w
dot_xv = np.dot(x, v)  # Dot product between matrix x and vector v
dot_xy = np.dot(x, y)  # Dot product between matrices x and y
print("Dot Product of v and w:", dot_vw)
print("Dot Product of x and v:", dot_xv)
print("Dot Product of x and y:\n", dot_xy)
print("---------------")

# 6. Concatenate arrays x and y along the rows, and v and w along the columns
concatenate_rows = np.concatenate((x, y), axis=0)  # Stacking x and y vertically (along rows)
concatenate_columns = np.vstack((v, w))  # Stacking v and w along the columns
print("Concatenate x and y along rows:\n", concatenate_rows)
print("Concatenate v and w along columns:\n", concatenate_columns)
print("---------------")

# 7. Attempt to concatenate x and v (will raise a shape mismatch error)
try:
    concatenate_xv = np.concatenate((x, v))  # This will fail due to shape mismatch
except ValueError as e:
    print("Error:", e)  # Display the error when the shapes are incompatible
    print("Explanation: x (2x2) and v (2,) cannot be concatenated due to shape mismatch.")


Addition of x and y:
 [[ 6  8]
 [10 13]]
---------------
Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]
---------------
Multiplication of x by 2:
 [[ 2  4]
 [ 6 10]]
---------------
Square of Each Element in x:
 [[ 1  4]
 [ 9 25]]
---------------
Dot Product of v and w: 219
Dot Product of x and v: [29 77]
Dot Product of x and y:
 [[19 22]
 [50 58]]
---------------
Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 10]
 [11 12]]
---------------
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: x (2x2) and v (2,) cannot be concatenated due to shape mismatch.


# Problem - 4: Matrix Operations:

In [20]:
import numpy as np

# Given arrays
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A^-1 = I (Identity Matrix Verification)
A_inv = np.linalg.inv(A)  # Compute inverse of matrix A
identity_check = np.dot(A, A_inv)  # Multiply A by its inverse, expecting the identity matrix
print("A.A^-1:\n", identity_check)
print("---------------")

# 2. Prove AB != BA (Non-commutativity of Matrix Multiplication)
AB = np.dot(A, B)  # Compute AB
BA = np.dot(B, A)  # Compute BA
print("AB:\n", AB)
print("BA:\n", BA)
print("Is AB != BA?", not np.array_equal(AB, BA))  # Check if AB is not equal to BA
print("---------------")

# 3. Prove (AB)^T = B^T A^T (Property of Transpose)
AB_transpose = AB.T  # Compute the transpose of AB
B_transpose_A_transpose = np.dot(B.T, A.T)  # Multiply the transposes of B and A
print("(AB)^T:\n", AB_transpose)
print("B^T A^T:\n", B_transpose_A_transpose)
print("Is (AB)^T == B^T A^T?", np.array_equal(AB_transpose, B_transpose_A_transpose))  # Check the property
print("---------------")

# Solve the system of linear equations
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Matrix form: AX = B
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])  # Coefficient matrix A_eq
B_eq = np.array([-1, -3, 9])  # Right-hand side values B_eq
print("---------------")

# Solve using the inverse method
X = np.dot(np.linalg.inv(A_eq), B_eq)  # Solve using the inverse of A_eq
print("Solution using Inverse Method:", X)
print("---------------")

# Solve using np.linalg.solve
X_solve = np.linalg.solve(A_eq, B_eq)  # Solve using numpy's built-in solver
print("Solution using np.linalg.solve:", X_solve)


A.A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
---------------
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Is AB != BA? True
---------------
(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]
Is (AB)^T == B^T A^T? True
---------------
---------------
Solution using Inverse Method: [ 2.  1. -2.]
---------------
Solution using np.linalg.solve: [ 2.  1. -2.]


# Experiment: How Fast is Numpy?

In [21]:
import time
import numpy as np

# Function to measure time taken for an operation
def measure_time(func, *args):
    start_time = time.time()  # Capture start time before executing function
    func(*args)  # Call the function with arguments
    end_time = time.time()  # Capture end time after execution
    return end_time - start_time  # Return the elapsed time

# 1. Element-wise Addition
def elementwise_addition_python(list1, list2):
    return [a + b for a, b in zip(list1, list2)]  # Perform element-wise addition using Python lists

def elementwise_addition_numpy(array1, array2):
    return array1 + array2  # Perform element-wise addition using NumPy arrays

# 2. Element-wise Multiplication
def elementwise_multiplication_python(list1, list2):
    return [a * b for a, b in zip(list1, list2)]  # Perform element-wise multiplication using Python lists

def elementwise_multiplication_numpy(array1, array2):
    return array1 * array2  # Perform element-wise multiplication using NumPy arrays

# 3. Dot Product
def dot_product_python(list1, list2):
    return sum(a * b for a, b in zip(list1, list2))  # Compute dot product using Python lists

def dot_product_numpy(array1, array2):
    return np.dot(array1, array2)  # Compute dot product using NumPy arrays

# 4. Matrix Multiplication
def matrix_multiplication_python(matrix1, matrix2):
    result = [[sum(a * b for a, b in zip(row, col)) for col in zip(*matrix2)] for row in matrix1]  # Matrix multiplication using Python lists
    return result

def matrix_multiplication_numpy(matrix1, matrix2):
    return np.dot(matrix1, matrix2)  # Matrix multiplication using NumPy arrays

# Initialize data
size = 1000000  # Define the size of arrays for element-wise operations
list1 = list(range(size))  # Initialize a list of integers from 0 to size-1
list2 = list(range(size, 2 * size))  # Initialize another list from size to 2*size-1
array1 = np.arange(size)  # Initialize a NumPy array from 0 to size-1
array2 = np.arange(size, 2 * size)  # Initialize another NumPy array from size to 2*size-1

matrix_size = 1000  # Define the size of the matrices for matrix multiplication
matrix1 = [[i + j for j in range(matrix_size)] for i in range(matrix_size)]  # Create a matrix of size matrix_size x matrix_size
matrix2 = [[i - j for j in range(matrix_size)] for i in range(matrix_size)]  # Create another matrix of size matrix_size x matrix_size
np_matrix1 = np.array(matrix1)  # Convert matrix1 into a NumPy array
np_matrix2 = np.array(matrix2)  # Convert matrix2 into a NumPy array

# Measure time for each operation
print("1. Element-wise Addition:")
time_python_add = measure_time(elementwise_addition_python, list1, list2)
time_numpy_add = measure_time(elementwise_addition_numpy, array1, array2)
print(f"Python Lists: {time_python_add:.6f} seconds")
print(f"NumPy Arrays: {time_numpy_add:.6f} seconds")

print("\n2. Element-wise Multiplication:")
time_python_mul = measure_time(elementwise_multiplication_python, list1, list2)
time_numpy_mul = measure_time(elementwise_multiplication_numpy, array1, array2)
print(f"Python Lists: {time_python_mul:.6f} seconds")
print(f"NumPy Arrays: {time_numpy_mul:.6f} seconds")

print("\n3. Dot Product:")
time_python_dot = measure_time(dot_product_python, list1, list2)
time_numpy_dot = measure_time(dot_product_numpy, array1, array2)
print(f"Python Lists: {time_python_dot:.6f} seconds")
print(f"NumPy Arrays: {time_numpy_dot:.6f} seconds")

print("\n4. Matrix Multiplication:")
time_python_matmul = measure_time(matrix_multiplication_python, matrix1, matrix2)
time_numpy_matmul = measure_time(matrix_multiplication_numpy, np_matrix1, np_matrix2)
print(f"Python Lists: {time_python_matmul:.6f} seconds")
print(f"NumPy Arrays: {time_numpy_matmul:.6f} seconds")


1. Element-wise Addition:
Python Lists: 0.219140 seconds
NumPy Arrays: 0.003738 seconds

2. Element-wise Multiplication:
Python Lists: 0.151967 seconds
NumPy Arrays: 0.001292 seconds

3. Dot Product:
Python Lists: 0.115533 seconds
NumPy Arrays: 0.000958 seconds

4. Matrix Multiplication:
Python Lists: 83.482245 seconds
NumPy Arrays: 0.842841 seconds
